test:
  workers:
    type: local
    number: 1
  rounds:
    - label: init
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      workload:
        module: benchmarks/samples/fabric/marbles/init.js
    - label: update
      txNumber: 499
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      workload:
        module: benchmarks/samples/fabric/marbles/update.js