version: '3'

networks:
  mongoCluster:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1

services:

  primary:
    container_name: primary
    image: mongo:5
    command: mongod --port 27017 --replSet myReplicaSet
    networks:
      mongoCluster:
        ipv4_address: 192.168.5.2
    ports:
      - 27017
    
  mongo1:
    container_name: mongo1
    command: mongod --port 27017 --replSet myReplicaSet
    image: mongo:5
    networks:
      mongoCluster:
        ipv4_address: 192.168.5.3
    ports:
      - 27017
    
  mongo2:
    container_name: mongo2
    image: mongo:5
    command: mongod --port 27017 --replSet myReplicaSet
    networks:
      mongoCluster:
        ipv4_address: 192.168.5.4
    ports:
      - 27017

  mongo3:
    container_name: mongo3
    command: mongod --port 27017 --replSet myReplicaSet
    image: mongo:5
    networks:
      mongoCluster:
        ipv4_address: 192.168.5.5
    ports:
      - 27017